#!/usr/bin/env node
// -*-js3-*-

var _       = require('lodash');
var program = require('commander');
var kue     = require('kue');
var redis   = require('redis');

program
.option('-s, --state <complete|failed|active|inactive>', 'Which state to delete')
.option('-q, --queue <name of queue>', 'Name of the queue to delete')
.option('-p, --port <int>' , 'Server port')
.option('-h, --host <string>' , 'Server hostname')
.parse(process.argv);

var state = program.state;
if(!state){
  console.log("must provide state -s");
  process.exit();
}

var config = {
    host : program.host ? program.host : 'localhost'
  , port : program.port ? program.port : 6379
};

kue.redis.createClient = function(){ return redis.createClient(config.port, config.host); };

var q = kue.createQueue();
var r = kue.redis.createClient();

if(program.queue) kue.Job.rangeByType(program.queue,program.state,0,-1,"asc",delete_jobs) // FIXME: this won't work, delivers jobs not IDs
else              q[state].call(q,delete_jobs);

function delete_jobs(err,job_ids){
  if(err) throw err;

  console.log(job_ids.length + " jobs");

  var fin = _.after(job_ids.length, process.exit);

  job_ids.forEach(function(id){
    kue.Job.get(id,function(err,job){
      if(err){
        if(err.message.match(/doesnt exist$/)){
          console.log(err.message);
          r.zrem(['q:jobs:'+state].concat([id]),function(err){
            if(err) console.dir(err);
            fin();
          });
        }
      }
      else if(!job){ // this is a q:job:[id] record sans "type" attribute, which causes kue to return nothing here, lame
        console.log("No job for id:" + id);
        r.del(['q:job:'+id],function(err){
          if(err) console.dir(err);
          fin();
        });
      }
      else{
        job.remove(function(err){
          if(err) console.dir(err);
          else    console.log("REMOVED: " + id);
          fin();
        });
      }
    });
  });
}
